<a href="https://colab.research.google.com/github/Chetirebochki/PythonLibruary/blob/main/numpybasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Напишите программу NumPy, чтобы проверить, являются ли два массива поэлементно равными в пределах допуска

In [22]:
import numpy as np
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

False
True


19. Напишите программу NumPy для создания вектора со значениями в диапазоне от 15 до 55 и распечатайте все значения, кроме первого и последнего.  


In [3]:
import numpy as np
v = np.arange(15,55)
print("Вектор:")
print(v)
print("Все значения кроме первого и последнего:")
print(v[1:-1])

Вектор:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
Все значения кроме первого и последнего:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


29. Напишите программу NumPy для создания нулевой матрицы 5x5 с элементами на главной диагонали, равными 1, 2, 3, 4, 5.  


In [4]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


9. Напишите программу NumPy, чтобы добавить границу (заполненную нулями) вокруг существующего массива.  



In [5]:
import numpy as np
x = np.ones((3,3))
print("Основная матрица:")
print(x)
print("нулики вокруг основной матрицы")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Основная матрица:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
нолики вокруг основной матрицы
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


19. Напишите программу NumPy, чтобы получить уникальные элементы массива.  


In [19]:
x = np.array([10, 10, 20, 20, 30, 30])
xx = np.unique(x)
z = np.array([[1, 1] ,[2, 3]])
zz = np.unique(z)
print(x)
print(xx)
print(z)
print(zz)

[10 10 20 20 30 30]
[10 20 30]
[[1 1]
 [2 3]]
[1 2 3]


Напишите программу NumPy для сортировки по первой, последней оси массива.  


In [21]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print(a)
print(' ')
x = np.sort(a, axis=0)
print(x)
print(' ')
y = np.sort(x, axis=-1)
print(y)

[[4 6]
 [2 1]]
 
[[2 1]
 [4 6]]
 
[[1 2]
 [4 6]]


 9. Напишите программу NumPy для вычисления число обусловленности данной матрицы.



In [23]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Матрица:")
print(a)
print("Число обусловленности:")
print(LA.cond(a))

Матрица:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
Число обусловленности:
1.4142135623730951


 19. Напишите программу NumPy для вычисления нормы Фробениуса и номера условия данного массива.

In [25]:
import numpy as np
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Матрица:")
print(a)
print("фробениус и Число обусловленности :")
print(np.linalg.norm(a, 'fro'))
print(np.linalg.cond(a, 'fro'))

Матрица:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
фробениус и Число обусловленности :
2.23606797749979
3.1622776601683795


Напишите программу NumPy, чтобы найти ближайшее значение из заданного значения в массиве.  


In [27]:
import numpy as np
x = np.array([[10, 0, -3], [12, 4, 2], [2, 5, 6]])
v = -2
n = x.flat[np.abs(x - v).argmin()]
print(n)

-3


Напишите программу NumPy для округления элементов массива до ближайшего целого числа.  


In [28]:
import numpy as np
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print("Массив:")
print(x)
x = np.rint(x)
print("Массив с округлением элементов:")
print(x)

Массив:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Массив с округлением элементов:
[-1. -2. -2.  0.  2.  2.  2.]


Напишите программу NumPy для вычисления среднего по измерению в двумерном массиве.  


In [29]:
import numpy as np
x = np.array([[10, 30], [20, 60]])
print("Массив:")
print(x)
print("Ср знач для столбца:")
print(x.mean(axis=0))
print("Ср знач для ряда:")
print(x.mean(axis=1))

Массив:
[[10 30]
 [20 60]]
Ср знач для столбца:
[15. 45.]
Ср знач для ряда:
[20. 40.]


Напишите программу NumPy для вычисления разницы между соседними элементами, поэлементно для данного массива.  


In [30]:
import numpy as np
x = np.array([1, 3, 5, 7, 0])
print(x)
print(np.diff(x))

[1 3 5 7 0]
[ 2  2  2 -7]


. Напишите программу NumPy для вычисления взаимной корреляции двух заданных массивов.  

In [31]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nX:")
print(x)
print("\nY:")
print(y)
print("\nКорреляция двух массивов\n",np.cov(x, y))


X:
[0 1 3]

Y:
[2 4 5]

Корреляция двух массивов
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


Напишите программу NumPy, чтобы удалить конечные пробелы всех элементов данного массива.  




In [33]:
import numpy as np
x = np.array([' python упражнения ', ' PHP  ', ' java  ', '  C++'])
print("Массив:")
print(x)
rstripped_char = np.char.rstrip(x)
print("\nУбрали пробелы : ", rstripped_char)

Массив:
[' python упражнения ' ' PHP  ' ' java  ' '  C++']

Убрали пробелы :  [' python упражнения' ' PHP' ' java' '  C++']


18. Напишите программу NumPy, чтобы проверить, начинается ли каждый элемент данного массива с «P».  


In [34]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'JS', 'пример', 'html'])
print("\nМассив:")
print(x1)
print("Проверка на начало на букву 'P':")
r = np.char.startswith(x1, "P")
print(r)


Массив:
['Python' 'PHP' 'JS' 'пример' 'html']
Проверка на начало на букву 'P':
[ True  True False False False]
